# Generated by Django 4.1.7 on 2023-04-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projects",
            options={"verbose_name_plural": "Projects"},
        ),
    ]
