# Generated by Django 4.1.7 on 2023-04-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogs_items",
            options={"verbose_name_plural": "Blogs Posts"},
        ),
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default="#ffffff", max_length=50),
        ),
    ]
