# Generated by Django 4.1.7 on 2023-04-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_category_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                choices=[
                    ("bg-yellow-500", "Yellow"),
                    ("bg-pink-500", "Pink"),
                    ("bg-orange-500", "Orange"),
                    ("bg-blue-500", "Blue"),
                ],
                default="bg-orange-500",
                max_length=50,
            ),
        ),
    ]
