# Generated by Django 4.1.7 on 2023-04-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0008_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.AddField(
            model_name="blogs_items",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
