# Generated by Django 4.1.7 on 2023-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0009_remove_like_user_blogs_items_view_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs_items",
            name="likes",
        ),
        migrations.AddField(
            model_name="blogs_items",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
