# Generated by Django 4.1.7 on 2023-04-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0012_alter_category_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs_items",
            name="tags",
        ),
    ]
