# Generated by Django 4.1.7 on 2023-04-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0013_remove_blogs_items_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs_items",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
